<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>f75dbfd2-ee3c-45d9-8e31-965f2953f274</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Exceptions\**" />
		<EmbeddedResource Remove="Exceptions\**" />
		<None Remove="Exceptions\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Defra.PTS.Web.Domain\Defra.PTS.Web.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Extensions\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.21.0" />
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
		<PackageReference Include="Defra.Trade.Address.V1.ApiClient" Version="1.0.9" />
		<PackageReference Include="Defra.Trade.Common.Config" Version="1.2.0" />
		<PackageReference Include="Defra.Trade.Common.Security" Version="4.0.3" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
	</ItemGroup>

</Project>
